version: '3'
services:
  #Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: gcc.shulepoint.co.ke, gccwelfare.shulepoint.co.ke
    volumes:
      - ./conf.d:/etc/nginx/conf.d/
      - letsencrypt:/etc/letsencrypt
      
volumes:
  letsencrypt:
    driver: local